### ISSUE TITLE
  Class Pureclarity\Core\Console\Command\RunFeed\All does not exist

### ISSUE THREAD

**Issue by R-K-Shrivastaw** [PureClarity/pureclarity-magento-2#58] opened 2019-12-23 08:08 UTC
After successful installation the pureclarity in Magento 2.3.0,  when enabing the Pureclarity module via command line getting an error like the below. 
`  Class Pureclarity\Core\Console\Command\RunFeed\All does not exist
`
Can anyone suggest why this is happening.  As I am getting somewhere feed is missing, so how to add feed?

**Comment by pcGarethJames** [comment] 2019-12-23 09:37
Hi,

The class "Pureclarity\Core\Console\Command\RunFeed\All" should exist in the directory: 

Console/Command/RunFeed

Within the vendor/pureclarity/pureclarity-magento-2/ module folder.

What classes do you have in that folder? 

For reference, which version of the plugin have you got installed?

**Comment by R-K-Shrivastaw** [comment] 2019-12-23 11:27
We installed the plugin version 3.0.1 from the magento marketplace.

**Comment by pcGarethJames** [comment] 2019-12-23 11:51
Hi,

That version of the plugin contains the "Pureclarity\Core\Console\Command\RunFeed\All" class (see https://github.com/PureClarity/pureclarity-magento-2/tree/3.0.1/Console/Command/RunFeed), please can you check the following:

1. The file Console/Command/RunFeed/All.php within the PureClarity module folder exists. If you installed via composer, it will be in vendor/pureclarity/pureclarity-magento-2/, if you downloaded & installed manually it will be in app/code/Pureclarity/Core. 

2. Ensure this file has correct permissions. It should be owned & readable by the same user as the rest of your Magento installation, this is usually the nginx / apache user (e.g. www-data)

3. When running module:enable for Pureclarity_Corem ensure you run the command as the correct user, i.e. the same user that owns all the files in the Magento installation, so that Magento can read the necessary files.

**Comment by pcGarethJames** [comment] 2019-12-23 18:42
As discussed by email, This was caused by the module being installed in app/code/pureclarity/pureclarity/. Changing this to app/code/Pureclarity/Core resolved the issue.

**Closed by pcGarethJames** 2019-12-23 18:42 UTC
